### ISSUE TITLE
Command line output / plaintext markdown friendliness

### ISSUE THREAD

**Issue by sambnh** [matb33/docx2md#10]
There are a few changes that could be made to improve the look of the converted markdown files in their plaintext form.

- Wrap any text that goes beyond 80 columns while maintaining correct syntax.
  - Would improve readability of the markdown in the command line.
  - Would not be possible to implement with tables as rows must all be on one line.
- Add a new line to the end of the generated files.
  - Would move the command line prompt onto a new line
- Give correct numbering to ordered lists instead of just using '1's
  - Would allow the number ordering to be visible in command line.

**Comment by u01jmg3** [comment]
> _Wrap any text that goes beyond 80 columns while maintaining correct syntax._

This is more about what command prompt you are using. For example I use the native Windows cmd which supports text wrapping. Equally in my editor (N++) I can choose whether to turn word wrapping on/off when editing Markdown files.

> _Add a new line to the end of the generated files._

Again I think this is more to do with how your command prompt is setup.

> _Give correct numbering to ordered lists instead of just using '1's_

Unfortunately using for example `1.1` is not supported in Markdown. Sticking with the prefix `1.` on all ordered list items will enable Markdown to take care of the numbering for you (e.g. `1.`, `2.`, etc.)

**Comment by sambnh** [comment]
>This is more about what command prompt you are using.

That is true, however the text wrapping of command lines and of more lightweight text editors such as vim, nano and emacs doesn't maintain indentation. Of course more advanced text editors indent wrapped text but it can be good to improve usability for edge cases and it can be cumbersome to have to open a separate program to just read text.

>Again I think this is more to do with how your command prompt is setup.

I expect this is more of a Linux thing as most commands will end with a new line. However, I'm sure it won't be too difficult to write some bash to check if the last outputted character was a new line and in the case it isn't, add it to the start of the prompt.

>Unfortunately using for example 1.1 is not supported in Markdown. Sticking with the prefix 1. on all ordered list items will enable Markdown to take care of the numbering for you (e.g. 1., 2., etc.)

Seeing your answer from [Issue #9](https://github.com/matb33/docx2md/issues/9#issuecomment-450596810) helped me understand this a bit more. I was mostly suggesting to add the ordering to the plaintext so that the numbering is visible without having to look at the rich text preview.
