### ISSUE TITLE
Table of Contents

### ISSUE THREAD

**Issue by sambnh** [matb33/docx2md#11]
A table of contents can be created in docx file which contains a list of all the headings. It would be desirable ensure a table of contents can be kept when a file is converted to markdown. A possible way of implementing this would be to give users an option, in the command line, to create a table of contents for the generated markdown. All it would be required to do is add links at the start of the file that link to all of the headings in order. The pre-existing code for links could also possibly be reused to achieve this.

**Comment by u01jmg3** [comment]
Meantime you could try [`caseyamcl/toc`](https://github.com/caseyamcl/toc) in combination with [`erusev/parsedown`](https://github.com/erusev/parsedown)

**Comment by sambnh** [comment]
Thanks, I'll give it a go
