### ISSUE TITLE
PHP Warnings generated by ms_split(), count() and implode().

### ISSUE THREAD

**Issue by sambnh** [matb33/docx2md#9]
The following warnings are output multiple times into the console upon converting a file.
```
PHP Warning:  mb_split(): mbregex compile err: invalid code point value in /docx2md/docx2md.php on line 565
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /docx2md/docx2md.php on line 566
PHP Warning:  implode(): Invalid arguments passed in /docx2md/docx2md.php on line 567
Performing conversion... finished √ 
```
The outputted markdown is a mess of numbers, dashes and asterisks which are presumably for lists as well as emboldening and italicising for the original text which is not present. Here's and example
```
 1.
 -
   -
   -
   -
   -
 - **__**__
 - **__**__
 - **__**__
   -
   -
 - __**__**__
 - __**__**__
 - __**__**__
 - __**__**__
   1.
 - __**__**__
   -
   -
 - __**__**__
 - **__**__
   -
   -
```

**Comment by archfrog** [comment]
Sorry to interrupt, but you may want to try if [Writage](http://www.writage.com/) is suitable for your needs.  Writage is an Office Word plugin, not a command-line utility, though.  And it doesn't support images just yet, as far as their website says.

I'm not sure if this project has been abandoned, but there has been no changes for a couple of years.

**Comment by u01jmg3** [comment]
> The following warnings are output multiple times into the console upon converting a file.

Without the file in question I can't begin to look at what the problem might be. Also it is helpful to know what version of PHP you are running.

> Sorry to interrupt, but you may want to try if Writage is suitable for your needs. Writage is an Office Word plugin, not a command-line utility, though.

Thanks for the recommendation but happy with this repo and script

> I'm not sure if this project has been abandoned, but there has been no changes for a couple of years.

Latest commit 52da9f9 on 19 Oct so the project is not abandoned

**Comment by sambnh** [comment]
> Without the file in question I can't begin to look at what the problem might be.

Of course, here's the input [notes.docx](https://github.com/matb33/docx2md/files/2716500/notes.docx) (a cutdown version of the original which still outputs the same warnings) and the output [notes.txt](https://github.com/matb33/docx2md/files/2716505/notes.txt) (as .txt because .md is not supported as an attachment).
> Also it is helpful to know what version of PHP you are running.

I'm running PHP 7.2.13, I have previously searched the issue for simple fixes and I found a fix to a similar issue with PHP 7.2 on [another repo](https://github.com/u01jmg3/ics-parser/commit/539ce70a884dbaceaa9cdf6b4bde03ed6c7045de).
> Sorry to interrupt, but you may want to try if Writage is suitable for your needs. Writage is an Office Word plugin, not a command-line utility, though.

I would consider using this, however I don't currently have MS Office installed so a command-line utility is what I'm looking for.

**Comment by u01jmg3** [comment]
`dev-master` should fix things for you: [notes.zip](https://github.com/matb33/docx2md/files/2716642/notes.zip)

**Comment by sambnh** [comment]
Thank you very much!
There are a few formatting issues still, would you like me to me to add them to a new issue?

**Comment by u01jmg3** [comment]
Go for it - always happy to improve the conversion process

**Comment by u01jmg3** [comment]
Further improvements have been made: see [`v1.0.3`](https://github.com/matb33/docx2md/releases/tag/v1.0.3)

**Comment by sambnh** [comment]
>Unwanted spacing between words

Reconverted the [notes.docx](https://github.com/matb33/docx2md/files/2716500/notes.docx) and this appears to have been resolved, nice job!

>The wrong list levels used by '1.1 Processors' and '1.2 Memory'

List levels has been fixed, however they are still not headings. I expect this will be trickier to fix as, in the notes.docx file, they are both actually listed headings which are not actually supported in markdown.  For example,
```
# 1. Heading 1
# 1. Heading 2
# 1. Heading 3
```
Outputs:
# 1. Heading 1
# 1. Heading 2
# 1. Heading 3
Meaning that list item cannot be created by putting the dash (-) or number (1.) after the hash (#), and if it occurs before the hash as follows
```
1. # Heading 1
1. # Heading 2
1. # Heading 3
```
It outputs:
1. # Heading 1
1. # Heading 2
1. # Heading 3
Which is ugly.

I would say for the best looking solution, using the notes.docx example, would be to treat the ordered list number (1, 1.1, 1.2 and so on) as part of the heading, as follows
```
# 1 Operating Systems Overview
## 1.1 Processors
## 1.2 Memory
```
Which outputs:
# 1 Operating Systems Overview
## 1.1 Processors
## 1.2 Memory
I think that just getting these listed headings to be converted to markdown headings should be the priority, over making them listed and looking nice.

**Comment by sambnh** [comment]
I have some other issues to raise other than the ones you found. However they are more like desirable features than bugs so I'll make different issue threads for them.
